### ISSUE TITLE
Error while executing commit

### ISSUE THREAD

**Issue by TobiasRadtke0770** [fr3dch3n/commit#4]
Hi Fr3dch3n,

we are getting the following Error:

panic: json: cannot unmarshal string into Go struct field State.pair of type []string

goroutine 1 [running]:
github.com/fr3dch3n/commit/utils.Check(...)
	/Users/foo/xxx/sources/other/commit/utils/errors.go:10
github.com/fr3dch3n/commit/cmd.commit()
	/Users/foo/xxx/sources/other/commit/cmd/root.go:101 +0x1406
github.com/fr3dch3n/commit/cmd.glob..func1(0x13b1240, 0x13ddf08, 0x0, 0x0)
	/Users/foo/xxx/sources/other/commit/cmd/root.go:45 +0x20
github.com/spf13/cobra.(*Command).execute(0x13b1240, 0xc0001101b0, 0x0, 0x0, 0x13b1240, 0xc0001101b0)
	/Users/foo/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x13b1240, 0x10414da, 0x139c440, 0xc000000180)
	/Users/foo/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/foo/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
github.com/fr3dch3n/commit/cmd.Execute()
	/Users/foo/xxx/sources/other/commit/cmd/root.go:51 +0x31
main.main()
	/Users/foo/xxx/sources/other/commit/main.go:8 +0x20

**Comment by fr3dch3n** [comment]
The last commit was a breaking-change in the state.
So you have to remove the ~/.commit-config.state file once.

**Comment by TobiasRadtke0770** [comment]
👍Thanks
